services:
  
  music_buddy:
    container_name: music-buddy
    build: .
    image: music-buddy:latest
    ports:
      - 5000:8000
    volumes:
      - ./music_buddy/database:/app/music_buddy/database
