services:
  
  music_buddy:
    container_name: music-buddy
    image: sneakymoon/music-buddy:main
    ports:
      - 5000:8000
    volumes:
      - models:/root/.cache
      - ./music:/music

volumes:
  models: