name: CI

on:
  pull_request:
    branches:
     - main
  push:
    branches:
      - main

env:
  APP_DIR: ./music_buddy
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    steps:
  
      - uses: actions/checkout@v4
  
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Check Formatting
        run: |
          uvx black --check .
          uvx isort --check-only .

      - name: Check linting
        run: |
          uvx ruff check .

      - name: Check Typing
        run: |
          uvx mypy $APP_DIR

      - name: Check security
        run: |
          uvx bandit --severity-level=medium -r $APP_DIR
